### ISSUE TITLE
video player available in custom pages

### ISSUE THREAD

**Issue by thoughtlead** [thoughtlead/ThoughtLead#27]
Right now we need to use external video players for our free opt-in launch videos. Having a player that we could embed in a custom page would be a huge help.

**Comment by wideopenspaces** [comment]
Bucket: tlpublic

I use S3hub (http://s3hub.com/) to access these buckets on a mac, and S3Fox (http://www.s3fox.net/) works well with Firefox on a PC.

Files uploaded to this bucket in S3 can be accessed by the URL

http://tlpublic.s3.amazonaws.com/name-of-file (where name-of-file is of course the name of the file you uploaded)

Let me know if you have any questions!

And here's the setup wizard for the JW Player -

http://www.longtailvideo.com/support/jw-player-setup-wizard
1. Under "Embed Parameters" change source to be "mediaplayer.swf" instead of player.swf (omit the quotes)
2. Under "File Properties" change file to the URL of the movie as determined above

There are other options you can change, such as the height and width of the player, but that can be determined to fit the design of the page. The above two are the only two you really need to set in order to get code for embedding.
